name: Testing

on:
  push:
    branches-ignore:
      - master

jobs:
  unittests:
    runs-on: ubuntu-latest
    steps:
      - name: error
        run: echo "::error file=script.js,line=10,col=15::Something went wrong"
      - name: error
        run: echo "::error file=ci.yml,line=10,col=15::Something went wrong"
